"""add market and agency workflow tables

Revision ID: faa2ca580bef
Revises: ed3c81770d54
Create Date: 2026-07-03 23:37:42.811254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'faa2ca580bef'
down_revision: Union[str, Sequence[str], None] = 'ed3c81770d54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_listings_raw',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('title_raw', sa.Text(), nullable=True),
    sa.Column('description_raw', sa.Text(), nullable=True),
    sa.Column('price_raw', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('city_raw', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=True),
    sa.Column('location_raw', sa.Text(), nullable=True),
    sa.Column('surface_raw', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('rooms_raw', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.Column('raw_data_hash', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_index(op.f('ix_market_listings_raw_external_id'), 'market_listings_raw', ['external_id'], unique=False)
    op.create_index(op.f('ix_market_listings_raw_first_seen_at'), 'market_listings_raw', ['first_seen_at'], unique=False)
    op.create_index(op.f('ix_market_listings_raw_last_seen_at'), 'market_listings_raw', ['last_seen_at'], unique=False)
    op.create_index(op.f('ix_market_listings_raw_raw_data_hash'), 'market_listings_raw', ['raw_data_hash'], unique=False)
    op.create_index(op.f('ix_market_listings_raw_source_id'), 'market_listings_raw', ['source_id'], unique=False)
    op.create_table('properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('description_summary', sa.Text(), nullable=True),
    sa.Column('property_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('transaction_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('rooms', sa.Integer(), nullable=True),
    sa.Column('surface_m2', sa.Float(), nullable=True),
    sa.Column('land_surface_m2', sa.Float(), nullable=True),
    sa.Column('floor', sa.Integer(), nullable=True),
    sa.Column('total_floors', sa.Integer(), nullable=True),
    sa.Column('year_built', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('address_text', sa.Text(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('opportunity_score', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_properties_city_id'), 'properties', ['city_id'], unique=False)
    op.create_index(op.f('ix_properties_created_at'), 'properties', ['created_at'], unique=False)
    op.create_index(op.f('ix_properties_opportunity_score'), 'properties', ['opportunity_score'], unique=False)
    op.create_index(op.f('ix_properties_property_type'), 'properties', ['property_type'], unique=False)
    op.create_index(op.f('ix_properties_quality_score'), 'properties', ['quality_score'], unique=False)
    op.create_index(op.f('ix_properties_rooms'), 'properties', ['rooms'], unique=False)
    op.create_index(op.f('ix_properties_surface_m2'), 'properties', ['surface_m2'], unique=False)
    op.create_index(op.f('ix_properties_transaction_type'), 'properties', ['transaction_type'], unique=False)
    op.create_table('scrape_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('listings_found', sa.Integer(), nullable=False),
    sa.Column('listings_inserted', sa.Integer(), nullable=False),
    sa.Column('listings_updated', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scrape_jobs_city_id'), 'scrape_jobs', ['city_id'], unique=False)
    op.create_index(op.f('ix_scrape_jobs_source_id'), 'scrape_jobs', ['source_id'], unique=False)
    op.create_index(op.f('ix_scrape_jobs_started_at'), 'scrape_jobs', ['started_at'], unique=False)
    op.create_index(op.f('ix_scrape_jobs_status'), 'scrape_jobs', ['status'], unique=False)
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('assigned_user_id', sa.Integer(), nullable=True),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('client_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('budget_min_eur', sa.Float(), nullable=True),
    sa.Column('budget_max_eur', sa.Float(), nullable=True),
    sa.Column('preferred_city_id', sa.Integer(), nullable=True),
    sa.Column('min_rooms', sa.Integer(), nullable=True),
    sa.Column('max_rooms', sa.Integer(), nullable=True),
    sa.Column('min_surface_m2', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['preferred_city_id'], ['cities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_assigned_user_id'), 'clients', ['assigned_user_id'], unique=False)
    op.create_index(op.f('ix_clients_budget_max_eur'), 'clients', ['budget_max_eur'], unique=False)
    op.create_index(op.f('ix_clients_budget_min_eur'), 'clients', ['budget_min_eur'], unique=False)
    op.create_index(op.f('ix_clients_client_type'), 'clients', ['client_type'], unique=False)
    op.create_index(op.f('ix_clients_created_at'), 'clients', ['created_at'], unique=False)
    op.create_index(op.f('ix_clients_email'), 'clients', ['email'], unique=False)
    op.create_index(op.f('ix_clients_full_name'), 'clients', ['full_name'], unique=False)
    op.create_index(op.f('ix_clients_organization_id'), 'clients', ['organization_id'], unique=False)
    op.create_index(op.f('ix_clients_phone'), 'clients', ['phone'], unique=False)
    op.create_index(op.f('ix_clients_preferred_city_id'), 'clients', ['preferred_city_id'], unique=False)
    op.create_table('market_listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_listing_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price_eur', sa.Float(), nullable=True),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('rooms', sa.Integer(), nullable=True),
    sa.Column('surface_m2', sa.Float(), nullable=True),
    sa.Column('price_per_m2', sa.Float(), nullable=True),
    sa.Column('property_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('transaction_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.ForeignKeyConstraint(['raw_listing_id'], ['market_listings_raw.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_index(op.f('ix_market_listings_city_id'), 'market_listings', ['city_id'], unique=False)
    op.create_index(op.f('ix_market_listings_first_seen_at'), 'market_listings', ['first_seen_at'], unique=False)
    op.create_index(op.f('ix_market_listings_last_seen_at'), 'market_listings', ['last_seen_at'], unique=False)
    op.create_index(op.f('ix_market_listings_price_eur'), 'market_listings', ['price_eur'], unique=False)
    op.create_index(op.f('ix_market_listings_price_per_m2'), 'market_listings', ['price_per_m2'], unique=False)
    op.create_index(op.f('ix_market_listings_property_type'), 'market_listings', ['property_type'], unique=False)
    op.create_index(op.f('ix_market_listings_raw_listing_id'), 'market_listings', ['raw_listing_id'], unique=False)
    op.create_index(op.f('ix_market_listings_rooms'), 'market_listings', ['rooms'], unique=False)
    op.create_index(op.f('ix_market_listings_source_id'), 'market_listings', ['source_id'], unique=False)
    op.create_index(op.f('ix_market_listings_surface_m2'), 'market_listings', ['surface_m2'], unique=False)
    op.create_index(op.f('ix_market_listings_transaction_type'), 'market_listings', ['transaction_type'], unique=False)
    op.create_table('organization_properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('assigned_user_id', sa.Integer(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organization_properties_assigned_user_id'), 'organization_properties', ['assigned_user_id'], unique=False)
    op.create_index(op.f('ix_organization_properties_created_at'), 'organization_properties', ['created_at'], unique=False)
    op.create_index(op.f('ix_organization_properties_organization_id'), 'organization_properties', ['organization_id'], unique=False)
    op.create_index(op.f('ix_organization_properties_property_id'), 'organization_properties', ['property_id'], unique=False)
    op.create_index(op.f('ix_organization_properties_status'), 'organization_properties', ['status'], unique=False)
    op.create_table('price_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('price_eur', sa.Float(), nullable=True),
    sa.Column('price_per_m2', sa.Float(), nullable=True),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_history_detected_at'), 'price_history', ['detected_at'], unique=False)
    op.create_index(op.f('ix_price_history_price_eur'), 'price_history', ['price_eur'], unique=False)
    op.create_index(op.f('ix_price_history_price_per_m2'), 'price_history', ['price_per_m2'], unique=False)
    op.create_index(op.f('ix_price_history_property_id'), 'price_history', ['property_id'], unique=False)
    op.create_index(op.f('ix_price_history_source_id'), 'price_history', ['source_id'], unique=False)
    op.create_table('opportunities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('market_listing_id', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('assigned_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['market_listing_id'], ['market_listings.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opportunities_assigned_user_id'), 'opportunities', ['assigned_user_id'], unique=False)
    op.create_index(op.f('ix_opportunities_client_id'), 'opportunities', ['client_id'], unique=False)
    op.create_index(op.f('ix_opportunities_created_at'), 'opportunities', ['created_at'], unique=False)
    op.create_index(op.f('ix_opportunities_market_listing_id'), 'opportunities', ['market_listing_id'], unique=False)
    op.create_index(op.f('ix_opportunities_organization_id'), 'opportunities', ['organization_id'], unique=False)
    op.create_index(op.f('ix_opportunities_property_id'), 'opportunities', ['property_id'], unique=False)
    op.create_index(op.f('ix_opportunities_score'), 'opportunities', ['score'], unique=False)
    op.create_index(op.f('ix_opportunities_status'), 'opportunities', ['status'], unique=False)
    op.create_table('property_market_listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('market_listing_id', sa.Integer(), nullable=False),
    sa.Column('similarity_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['market_listing_id'], ['market_listings.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_property_market_listings_market_listing_id'), 'property_market_listings', ['market_listing_id'], unique=False)
    op.create_index(op.f('ix_property_market_listings_property_id'), 'property_market_listings', ['property_id'], unique=False)
    op.create_index(op.f('ix_property_market_listings_similarity_score'), 'property_market_listings', ['similarity_score'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('assigned_user_id', sa.Integer(), nullable=True),
    sa.Column('related_client_id', sa.Integer(), nullable=True),
    sa.Column('related_property_id', sa.Integer(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('due_at', sa.DateTime(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['related_client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['related_property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_assigned_user_id'), 'tasks', ['assigned_user_id'], unique=False)
    op.create_index(op.f('ix_tasks_created_at'), 'tasks', ['created_at'], unique=False)
    op.create_index(op.f('ix_tasks_due_at'), 'tasks', ['due_at'], unique=False)
    op.create_index(op.f('ix_tasks_organization_id'), 'tasks', ['organization_id'], unique=False)
    op.create_index(op.f('ix_tasks_related_client_id'), 'tasks', ['related_client_id'], unique=False)
    op.create_index(op.f('ix_tasks_related_property_id'), 'tasks', ['related_property_id'], unique=False)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_index(op.f('ix_tasks_title'), 'tasks', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_title'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_related_property_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_related_client_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_organization_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_due_at'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_created_at'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_assigned_user_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_property_market_listings_similarity_score'), table_name='property_market_listings')
    op.drop_index(op.f('ix_property_market_listings_property_id'), table_name='property_market_listings')
    op.drop_index(op.f('ix_property_market_listings_market_listing_id'), table_name='property_market_listings')
    op.drop_table('property_market_listings')
    op.drop_index(op.f('ix_opportunities_status'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_score'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_property_id'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_organization_id'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_market_listing_id'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_created_at'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_client_id'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_assigned_user_id'), table_name='opportunities')
    op.drop_table('opportunities')
    op.drop_index(op.f('ix_price_history_source_id'), table_name='price_history')
    op.drop_index(op.f('ix_price_history_property_id'), table_name='price_history')
    op.drop_index(op.f('ix_price_history_price_per_m2'), table_name='price_history')
    op.drop_index(op.f('ix_price_history_price_eur'), table_name='price_history')
    op.drop_index(op.f('ix_price_history_detected_at'), table_name='price_history')
    op.drop_table('price_history')
    op.drop_index(op.f('ix_organization_properties_status'), table_name='organization_properties')
    op.drop_index(op.f('ix_organization_properties_property_id'), table_name='organization_properties')
    op.drop_index(op.f('ix_organization_properties_organization_id'), table_name='organization_properties')
    op.drop_index(op.f('ix_organization_properties_created_at'), table_name='organization_properties')
    op.drop_index(op.f('ix_organization_properties_assigned_user_id'), table_name='organization_properties')
    op.drop_table('organization_properties')
    op.drop_index(op.f('ix_market_listings_transaction_type'), table_name='market_listings')
    op.drop_index(op.f('ix_market_listings_surface_m2'), table_name='market_listings')
    op.drop_index(op.f('ix_market_listings_source_id'), table_name='market_listings')
    op.drop_index(op.f('ix_market_listings_rooms'), table_name='market_listings')
    op.drop_index(op.f('ix_market_listings_raw_listing_id'), table_name='market_listings')
    op.drop_index(op.f('ix_market_listings_property_type'), table_name='market_listings')
    op.drop_index(op.f('ix_market_listings_price_per_m2'), table_name='market_listings')
    op.drop_index(op.f('ix_market_listings_price_eur'), table_name='market_listings')
    op.drop_index(op.f('ix_market_listings_last_seen_at'), table_name='market_listings')
    op.drop_index(op.f('ix_market_listings_first_seen_at'), table_name='market_listings')
    op.drop_index(op.f('ix_market_listings_city_id'), table_name='market_listings')
    op.drop_table('market_listings')
    op.drop_index(op.f('ix_clients_preferred_city_id'), table_name='clients')
    op.drop_index(op.f('ix_clients_phone'), table_name='clients')
    op.drop_index(op.f('ix_clients_organization_id'), table_name='clients')
    op.drop_index(op.f('ix_clients_full_name'), table_name='clients')
    op.drop_index(op.f('ix_clients_email'), table_name='clients')
    op.drop_index(op.f('ix_clients_created_at'), table_name='clients')
    op.drop_index(op.f('ix_clients_client_type'), table_name='clients')
    op.drop_index(op.f('ix_clients_budget_min_eur'), table_name='clients')
    op.drop_index(op.f('ix_clients_budget_max_eur'), table_name='clients')
    op.drop_index(op.f('ix_clients_assigned_user_id'), table_name='clients')
    op.drop_table('clients')
    op.drop_index(op.f('ix_scrape_jobs_status'), table_name='scrape_jobs')
    op.drop_index(op.f('ix_scrape_jobs_started_at'), table_name='scrape_jobs')
    op.drop_index(op.f('ix_scrape_jobs_source_id'), table_name='scrape_jobs')
    op.drop_index(op.f('ix_scrape_jobs_city_id'), table_name='scrape_jobs')
    op.drop_table('scrape_jobs')
    op.drop_index(op.f('ix_properties_transaction_type'), table_name='properties')
    op.drop_index(op.f('ix_properties_surface_m2'), table_name='properties')
    op.drop_index(op.f('ix_properties_rooms'), table_name='properties')
    op.drop_index(op.f('ix_properties_quality_score'), table_name='properties')
    op.drop_index(op.f('ix_properties_property_type'), table_name='properties')
    op.drop_index(op.f('ix_properties_opportunity_score'), table_name='properties')
    op.drop_index(op.f('ix_properties_created_at'), table_name='properties')
    op.drop_index(op.f('ix_properties_city_id'), table_name='properties')
    op.drop_table('properties')
    op.drop_index(op.f('ix_market_listings_raw_source_id'), table_name='market_listings_raw')
    op.drop_index(op.f('ix_market_listings_raw_raw_data_hash'), table_name='market_listings_raw')
    op.drop_index(op.f('ix_market_listings_raw_last_seen_at'), table_name='market_listings_raw')
    op.drop_index(op.f('ix_market_listings_raw_first_seen_at'), table_name='market_listings_raw')
    op.drop_index(op.f('ix_market_listings_raw_external_id'), table_name='market_listings_raw')
    op.drop_table('market_listings_raw')
    # ### end Alembic commands ###
